#theme: jekyll-theme-slate
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "seek"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes:
        - wide