#theme: jekyll-theme-slate
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "seek"

include: ["_pages"]

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes:
        - wide

title: 'seek4science.org'

search: true
search_provider: google
google:
  search_engine_id: 000557171303025515437:vrcbow5ltbc
  instant_search: false