#theme: jekyll-theme-slate
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "seek"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes:
        - wide